sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarqube:
    branches:
      - sonar
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
language: node_js
node_js:
  - '6.5'
script:
  -  npm run coveralls && npm run test:integration && sonar-scanner
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
